### ISSUE TITLE
[Question] Futher work?

### ISSUE THREAD

**Issue by Pk13055** [debanshur/algotrading#14]
Hi, will you be developing this further? I'd love to have a chat regarding this project and it's potential conversion into something larger.

**Comment by debanshur** [comment]
Hi, Yes I am still developing it.
Could do much recently as i was busy with something else. Will resume this soon.

Would love to discuss with you on any future plan.

**Comment by Pk13055** [comment]
What's your email ID? Will follow through there!

**Comment by debanshur** [comment]
debanshur94@gmail.com
